import "./globals.css";
import type {Metadata} from "next";
import {Inter} from "next/font/google";
import Providers from "@/lib/providers";
import {DynamicWidget} from "@dynamic-labs/sdk-react-core";

import './page.css';

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
        <Providers>
            <body className={inter.className}>
                <div className={`container light`}>
                    <div className="header">
                        <div className="header-buttons">
                            <DynamicWidget></DynamicWidget>
                        </div>
                    </div>
                    <div className="modal">
                        {children}
                    </div>
                    <div className="footer">
                    </div>
                </div>
            </body>
        </Providers>
        </html>
    );
}